version: '3.8'

services:
  # Service MongoDB
  mongodb:
    image: mongo:4.4.16
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --config /etc/mongod.conf
    networks:
      - app-network

  # Service pour l'application Flask (optionnel)
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${FLASK_PORT}
      - FRONTEND_URL=http://${HOST}:${FRONTEND_PORT}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-network

  # Service pour le batch scheduler
  batch:
    build: .
    command: python app/services/batch_scheduler.py
    restart: always
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - PORT=${FLASK_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-network

  # Service pour l'application React
  react-app:
    build:
      context: ./spa
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./spa:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=${HOST}
      - FLASK_PORT=${FLASK_PORT}
      - VITE_API_BASE_URL=http://${HOST}:${FLASK_PORT}
    depends_on:
      - flask-app
    networks:
      - app-network


volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge